name: Build Jetson Images

on:
  push:
    tags:
      - "*"

env:
  L4T32_BSP: 32.7.4
  L4T35_BSP: 35.5.0
  L4T36_BSP: 36.3.0

jobs:
  build:
    strategy:
      matrix:
        ubuntu: ["22.04", "24.04"]

    permissions:
      contents: write
      packages: write
      id-token: write
      workflows: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Just
        uses: taiki-e/install-action@just

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y podman qemu-user-static pigz
          sudo systemctl start systemd-binfmt.service

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true

      - name: Create rootfs
        run: just build-jetson-rootfs ${{ matrix.ubuntu }}

      - name: Build Jetson Image for Jetson Nano Revision 300
        if: matrix.ubuntu == '22.04'
        run: |
          just build-jetson-image \
            -b jetson-nano \
            -r 300
          mv jetson.img "jetson-nano-300_${{ matrix.ubuntu }}_${L4T32_BSP}.img"
          pigz "jetson-nano-300_${{ matrix.ubuntu }}_${L4T32_BSP}.img"
          ls -lht "jetson-nano-300_${{ matrix.ubuntu }}_${L4T32_BSP}.img.gz"

      - name: Build Jetson Image for Jetson Nano Revision 200
        if: matrix.ubuntu == '22.04'
        run: |
          just build-jetson-image \
            -b jetson-nano \
            -r 200
          mv jetson.img "jetson-nano-200_${{ matrix.ubuntu }}_${L4T32_BSP}.img"
          pigz "jetson-nano-200_${{ matrix.ubuntu }}_${L4T32_BSP}.img"
          ls -lht "jetson-nano-200_${{ matrix.ubuntu }}_${L4T32_BSP}.img.gz"

      - name: Build Jetson Image for Jetson Nano Revision 100
        if: matrix.ubuntu == '22.04'
        run: |
          just build-jetson-image \
            -b jetson-nano \
            -r 100
          mv jetson.img "jetson-nano-100_${{ matrix.ubuntu }}_${L4T32_BSP}.img"
          pigz "jetson-nano-100_${{ matrix.ubuntu }}_${L4T32_BSP}.img"
          ls -lht "jetson-nano-100_${{ matrix.ubuntu }}_${L4T32_BSP}.img.gz"

      - name: Build Jetson Image for Jetson Nano 2GB
        if: matrix.ubuntu == '22.04'
        run: |
          just build-jetson-image \
            -b jetson-nano-2gb
          mv jetson.img "jetson-nano-2gb_${{ matrix.ubuntu }}_${L4T32_BSP}.img"
          pigz "jetson-nano-2gb_${{ matrix.ubuntu }}_${L4T32_BSP}.img"
          ls -lht "jetson-nano-2gb_${{ matrix.ubuntu }}_${L4T32_BSP}.img.gz"

      - name: Build Jetson Image for Jetson Orin Nano SD
        if: matrix.ubuntu == '24.04'
        run: |
          just build-jetson-image \
            -b jetson-orin-nano \
            -d SD \
            -l 36
          mv jetson.img "jetson-orin-nano_${{ matrix.ubuntu }}_${L4T36_BSP}_SD.img"
          pigz "jetson-orin-nano_${{ matrix.ubuntu }}_${L4T36_BSP}_SD.img"
          ls -lht "jetson-orin-nano_${{ matrix.ubuntu }}_${L4T36_BSP}_SD.img.gz"

      - name: Build Jetson Image for Jetson Orin Nano USB
        if: matrix.ubuntu == '24.04'
        run: |
          just build-jetson-image \
            -b jetson-orin-nano \
            -d USB \
            -l 36
          mv jetson.img "jetson-orin-nano_${{ matrix.ubuntu }}_${L4T36_BSP}_USB.img"
          pigz "jetson-orin-nano_${{ matrix.ubuntu }}_${L4T36_BSP}_USB.img"
          ls -lht "jetson-orin-nano_${{ matrix.ubuntu }}_${L4T36_BSP}_USB.img.gz"

      - name: Build Jetson Image for Jetson AGX Xavier SD
        if: matrix.ubuntu == '22.04'
        run: |
          just build-jetson-image \
            -b jetson-agx-xavier \
            -d SD \
            -l 35
          mv jetson.img "jetson-agx-xavier_${{ matrix.ubuntu }}_${L4T35_BSP}_SD.img"
          pigz "jetson-agx-xavier_${{ matrix.ubuntu }}_${L4T35_BSP}_SD.img"
          ls -lht "jetson-agx-xavier_${{ matrix.ubuntu }}_${L4T35_BSP}_SD.img.gz"

      - name: Build Jetson Image for Jetson AGX Xavier USB
        if: matrix.ubuntu == '22.04'
        run: |
          just build-jetson-image \
            -b jetson-agx-xavier \
            -d USB \
            -l 35
          mv jetson.img "jetson-agx-xavier_${{ matrix.ubuntu }}_${L4T35_BSP}_USB.img"
          pigz "jetson-agx-xavier_${{ matrix.ubuntu }}_${L4T35_BSP}_USB.img"
          ls -lht "jetson-agx-xavier_${{ matrix.ubuntu }}_${L4T35_BSP}_USB.img.gz"

      - name: Build Jetson Image for Jetson Xavier NX SD
        if: matrix.ubuntu == '22.04'
        run: |
          just build-jetson-image \
            -b jetson-xavier-nx \
            -d SD \
            -l 35
          mv jetson.img "jetson-xavier-nx_${{ matrix.ubuntu }}_${L4T35_BSP}_SD.img"
          pigz "jetson-xavier-nx_${{ matrix.ubuntu }}_${L4T35_BSP}_SD.img"
          ls -lht "jetson-xavier-nx_${{ matrix.ubuntu }}_${L4T35_BSP}_SD.img.gz"

      - name: Build Jetson Image for Jetson Xavier NX USB
        if: matrix.ubuntu == '22.04'
        run: |
          just build-jetson-image \
            -b jetson-xavier-nx \
            -d USB \
            -l 35
          mv jetson.img "jetson-xavier-nx_${{ matrix.ubuntu }}_${L4T35_BSP}_USB.img"
          pigz "jetson-xavier-nx_${{ matrix.ubuntu }}_${L4T35_BSP}_USB.img"
          ls -lht "jetson-xavier-nx_${{ matrix.ubuntu }}_${L4T35_BSP}_USB.img.gz"

      - name: Release Images
        uses: softprops/action-gh-release@v2
        with:
          body: |
            [CHANGELOG.md](${{ github.server_url }}/${{ github.repository }}/blob/master/CHANGELOG.md)
          files: "jetson*.gz"
