name: Build and Deploy Jetson Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-jetson-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Ansible and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible qemu-user-static binfmt-support

    - name: Create Jetson image
      run: |
        chmod +x create-image.sh
        ./create-image.sh

    - name: Flash Jetson image
      run: |
        chmod +x flash-image.sh
        ./flash-image.sh

    - name: Run Ansible playbook
      run: |
        ansible-playbook -i ansible/hosts.yaml ansible/jetson.yaml

  clean-up:
    runs-on: ubuntu-latest
    needs: build-jetson-image

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clean up Jetson
      run: |
        chmod +x clean_jetson.sh
        ./clean_jetson.sh
