network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: true
  wifis:
    wlan0:
      dhcp4: true
      dhcp4-overrides:
        use-dns: no
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
      access-points:
        YOUR_ACCESS_POINT:
          password: WIFI_PASSWORD
      addresses: []
      gateway4: 0.0.0.0
      routes:
        - to: 0.0.0.0/0
          via: <Your Ethernet Gateway IP>
          metric: 100
