name: ROS Humble YOLO Jetson Nano

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths-ignore:
      - README.md
  pull_request:
    branches: 
      - main
    paths-ignore:
      - README.md

env:
  REGISTRY: ghcr.io
  OWNER: kalanaratnayake
  IMAGE_NAME: yolo-ros

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write  # Add this if you're using GitHub Actions for authentication

    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        run: |
          echo ${{ secrets.GH_PAT }} | docker login ghcr.io --username ${{ env.OWNER }} --password-stdin

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.jetson-nano
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:latest-j-nano
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:humble-j-nano
