name: Build and Deploy Jetson Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-jetson-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List directory contents
        run: ls -al

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Ansible and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible qemu-user-static binfmt-support

      - name: Create Jetson image
        run: |
          if [ ! -f ./create-image.sh ]; then
            echo "create-image.sh not found!"
            exit 1
          fi
          chmod +x create-image.sh
          sudo -E ./create-image.sh

      - name: Flash Jetson image
        run: |
          if [ ! -f ./flash-image.sh ]; then
            echo "flash-image.sh not found!"
            exit 1
          fi
          chmod +x flash-image.sh
          sudo -E ./flash-image.sh

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ansible/hosts.yaml ansible/jetson.yaml

  clean-up:
    runs-on: ubuntu-latest
    needs: build-jetson-image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean up Jetson
        run: |
          if [ ! -f ./clean_jetson.sh ]; then
            echo "clean_jetson.sh not found!"
            exit 1
          fi
          chmod +x clean_jetson.sh
          sudo -E ./clean_jetson.sh
